musaJobs-BackEnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register'  => false,
    'reset'  => true,
    'verify'  => false,
]);

Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('users','UsersController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('companies','CompaniesController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('categories','CategoriesController');
});


Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('skills','SkillsController');
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('job-offers','JobOffersController')->except(['create','store']);
});

musaJobs-BackEnd/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;
    protected $fillable =
    [

        'name',
        'description',
        'city',
        'website',
        'logo',
        'category_id',
    ];

    protected $appends =
    [
        'company_logo_full_url',
    ];

    public function getCompanyLogoFullUrlAttribute()
    {
        return env('APP_URL') . 'storage/' . $this->logo;
    }

    public function jobOffers()
    {
        return $this->hasMany('App\Models\JobOffer','company_id','id');
    }
    public function user()
    {
        return $this->morphOne('App\Models\User','details'); //modello relazionato --- e il nome della relazione(details è quella che hai in user)
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category','category_id','id');
    }
}

musaJobs-BackEnd/app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use Illuminate\Http\Request;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::get();
        return view ('admin.companies.list',compact('companies'));
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::with([
            'user',
            'jobOffers' => function ($q)
            {
                $q->with(['statusHistory' => function($q)
                {
                    $q->orderByStatusHistory();
                }]);
            },
            'category'])
            ->findOrFail($id); //questi sono i nomi delle relazioni
        return view('admin.companies.details',compact('company') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

musaJobs-BackEnd/app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyLogoRequest;
use App\Models\Category;
use App\Models\Company;
use App\Traits\ApiTrait;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    use ApiTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(5);

        return response()->json( [ 'result' => $companies, 'code' => 200], 200 );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::findOrFail( $id );
        return response()->json( [ 'result' => $company, 'code' => 200], 200 );
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function updLoadLogo(CompanyLogoRequest $request)
    {
        $user = Auth::user();

        $company_logo = 'companies/default.png';

        $company = $user->details;

        if($company &&  $request->hasFile( 'logo' ))
        {
            $file = $request->file( 'logo' );
            $filename = time(). '.' . $file->getClientOriginalExtension(); // mette un nome generico al file
            $file_path = 'companies/' . $company->id . '/logo';
            $uploaded_file = $file->storeAs( $file_path,$filename,'public');
            $company->logo= $uploaded_file; // php artisan storage:link
            $company->save();

            return $this->successResponse(['logo_url' =>$company->company_logo_full_url],JsonResponse::HTTP_CREATED);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function allCategories()
    {
        $categories = Category::get()->all();
        return response()->json( [ 'result' => $categories, 'code' => 200], 200 );
    }
}

musaJobs-BackEnd/resources/views/admin/companies/details.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1> {{$company->name}} </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">

                @forelse( $company->jobOffers as $job_offer)
                    <li class="list-group-item">{{$job_offer->role}}</li>
                    <hr>
                    @foreach ($job_offer->statusHistory as $history_item)
                    <div class="d-flex justify-content-between">
                        <div>
                            {{$history_item->label}}
                        </div>
                        <div class="d-flex flex-column">
                            <div>
                                <strong>DA:</strong>
                                <span>{{$history_item->pivot->from}}</span>
                            </div>
                            <div>
                                <strong>A:</strong>
                                <span>{{$history_item->pivot->to}}</span>
                            </div>
                        </div>
                    </div>
                    @endforeach
                @empty
                    <li class="list-group-item active">Nessuan offerta di</li>
                @endforelse
            </ul>
        </div>
    </div>
</div>

@endsection

musaJobs-BackEnd/resources/views/admin/companies/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                @forelse($companies as $company)
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <div>
                            {{$company->name}}
                        </div>
                        <div>
                            <a href="{{route('admin.companies.show',['company' => $company->id])}}" class="btn btn-primary"> Details </a>
                        </div>
                    </div>
                </li>
                @empty
                <li class="list-group-item">
                    Non ci sono compagnie
                </li>
                @endforelse
            </ul>
        </div>
    </div>
</div>

@endsection