musaJobs-BackEnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register'  => false,
    'reset'  => true,
    'verify'  => false,
]);

Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('users','UsersController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('companies','CompaniesController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('categories','CategoriesController');
});


Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('skills','SkillsController');
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('job-offers','JobOffersController')->except(['create','store']);
});

musaJobs-BackEnd/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable =
    [
        'label',
        'code',
    ];

    public function companies()
    {
        return $this->hasMany('App\Models\Company','category_id','id');
    }

    public function scopeOrdered ($query)
    {
        return $query->orderBy('label','ASC');
    }
}

musaJobs-BackEnd/app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use XdgBaseDir\Xdg;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories= Category::get();
        return view('admin.categories.list',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.add-category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $category_data = $request->except([ '_token' ]);
        $category_code = Str::slug($category_data['label']);

        $exist = Category::where( 'code', $category_code)->first();


        if(!$exist)
        {
            $category_data['code'] = $category_code;

            $created = Category::create( $category_data );
            if($created)
            {

                session()->flash('success', __('labels.categories.created'));
                return redirect()->route('admin.categories.index');
            }
            else
            {
                session()->flash('error', __('labels.categories.errors.general'));
                return redirect()->back();
            }
        }
        else
        {
            session()->flash('error', __('labels.categories.errors.already_exist'));
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

musaJobs-BackEnd/resources/views/admin/categories/add-category.blade.php
@extends('layouts.app')

@section('content')
@if($errors->any())
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="alert alert-danger" role="alert">
                    <ul class="list-unstyled">
                        @foreach($errors->all() as $error)
                            <li>
                                {{$error}}
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
}
@endif


<form action="{{route('admin.categories.store')}}" method="POST">
    @csrf
    <div class="container">
        @include('admin.components.messages')
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label for="category-label">Label Categoria</label>
                    <input name="label" type="text" class="form-control" id="category-label"/>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <button type="submit" class="btn btn-primary">@lang('labels.save')</button>
                <a href="{{ route( 'admin.categories.index')}}" class="btn btn-danger">@lang('labels.back')</a>
            </div>
        </div>

    </div>

</form>

@endsection

musaJobs-BackEnd/resources/views/admin/categories/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('admin.components.messages')
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                @forelse($categories as $category)
                <li class="list-group-item">
                    {{$category->label}}
                </li>
                @empty
                <li class="list-group-item">
                    Non ci sono categorie
                </li>
                @endforelse
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a href="{{route ('admin.categories.create') }}" class="btn btn-primary">Nuova Categoria</a>
        </div>
    </div>
</div>

@endsection