musaJobs-BackEnd/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register'  => false,
    'reset'  => true,
    'verify'  => false,
]);

Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('users','UsersController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('companies','CompaniesController')->except(['create','store']);
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('categories','CategoriesController');
});


Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('skills','SkillsController');
});



Route::prefix('admin')->namespace('admin')->name('admin.')->middleware('can:can-admin')->group(function(){
    Route::resource('job-offers','JobOffersController')->except(['create','store']);
});

musaJobs-BackEnd/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->Fullname }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">


                                    <a class="dropdown-item" href="{{route('admin.users.index')}}">
                                        Gestione utenti
                                    </a>


                                    <a class="dropdown-item" href="{{route('admin.companies.index')}}">
                                        Gestione aziende
                                    </a>


                                    <a class="dropdown-item" href="{{route('admin.categories.index')}}">
                                        Gestione categorie azienda
                                    </a>


                                    <a class="dropdown-item" href="{{route('admin.job-offers.index')}}">
                                        Gestione annunci
                                    </a>


                                    <a class="dropdown-item" href="{{route('admin.skills.index')}}">
                                        Gestione skills
                                    </a>


                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>